import { Button, ListView, ComboBox , VerticalBox, TextEdit, HorizontalBox} from "std-widgets.slint";

global Theme  {
    out property<length> padding: 4px;
    out property<length> spacing: 4px;
    out property <length> leftPanelWidth: 200px;
    out property <length> buttonPanelHeight: 200px ;
    out property <length> headerHeight: 40px ;
}

export component AppWindow inherits Window {
    default-font-size: 20px;
    width: 840px;
    height: 600px;

    in-out property<[{text: string, color: color, bg: color, user: bool}]> datas: [
                        { text: "Blue\nejif", color: #0000ff, bg: #eeeeee, user: true},
                        { text: "Red", color: #ff0000, bg: #eeeeee, user: false},
                        { text: "Green", color: #00ff00, bg: #eeeeee, user: true},
                        { text: "Yellow", color: #ffff00, bg: #222222, user:false },
                    ];

    HorizontalLayout {
        padding: Theme.padding;
        spacing: Theme.spacing;

        VerticalLayout {
            spacing: Theme.spacing;
            width: Theme.leftPanelWidth;

            VerticalLayout {
                height: Theme.headerHeight;
                Button {
                    text: "New Session +";
                }
            }

            ListView {
                padding: 4px;
                for data in ["1", "2"] : VerticalLayout {
                    padding: Theme.padding * 2;
                    spacing: Theme.spacing * 2;
                    Text {
                        text: data;
                    }
                }
            }

            VerticalLayout {
                height: Theme.buttonPanelHeight;
                padding-top: Theme.padding * 4;

                VerticalLayout {
                    spacing: Theme.spacing;
                    Rectangle {
                        background: Colors.red;
                    }

                    Rectangle {
                        background: Colors.blue;
                    }

                    Rectangle {
                        background: Colors.yellow;
                    }
                }
                
            }
            
        }

        VerticalLayout {
            spacing: Theme.spacing;

            HorizontalLayout {
                height: Theme.headerHeight;
                
                ComboBox {
                    model: ["first", "second", "third"];
                    current-value: "first";
                }
            }

            ListView {
                padding: Theme.padding;
                for data in datas : VerticalLayout {
                    padding: Theme.padding * 2;
                    spacing: Theme.spacing * 2;
     
                    HorizontalLayout {
                        padding-bottom: Theme.padding;
                        alignment: space-between;
                        Rectangle {
                            height: 30px;
                            width: 30px;
                            background: Colors.red;
                            border-radius: self.height / 2;
                            visible: data.user;
                        }

                        Rectangle {
                            height: 30px;
                            width: 30px;
                            background: Colors.red;
                            visible: !data.user;
                            border-radius: self.height / 2;
                        }
                    }

                    Text {
                        width: parent.width;
                        text: data.text;
                        color: data.color;
                        wrap: word-wrap;
                    }

                    Rectangle {
                        background: Colors.steelblue;
                        width: 100%;
                        height: 1px;
                    }
                }
            }
                

            VerticalLayout {
                padding-top: Theme.padding * 4;
                spacing: Theme.spacing;
                height: Theme.buttonPanelHeight;

                TextEdit {
                    edited(text) => {}
                }
                
                HorizontalLayout {
                    alignment: space-between;

                    HorizontalLayout {
                        padding-right: Theme.padding;
                        width: 50%;
                        Button {
                            height: 30px;
                            text: "Reset";
                            clicked => {}
                        }
                    }
                    
                    HorizontalLayout {
                        padding-left: Theme.padding;
                        width: 50%;
                        Button {
                            height: 30px;
                            text: "Send";
                            clicked => {}
                        }
                    }
                } 
            }
         }
    }
}
