import { SessionConfig } from "./store.slint";

export global Logic {
    callback handle-new-session(SessionConfig);
    callback handle-edit-session(string);
    callback reset-current-session();
    callback delete-session(string);
    callback toggle-mark-session(string);
    callback handle-session-dialog(string, string);

    callback send-input-text(string);
    callback delete-chat-item(string);
    callback toggle-mark-chat-item(string);
    callback stop-generate_text();

    callback show-message(string, string);
    callback copy-to-clipboard(string);
    callback handle-ok-cancel-dialog(string, string);
}
