import { SessionConfig, SettingDialogConfig, CodeTextItem } from "./store.slint";

export global Logic {
    callback hide-window();

    callback handle-new-session(SessionConfig);
    callback save-edit-session(string, SessionConfig);
    callback set-edit-session(string);
    callback reset-edit-session();
    callback reset-current-session();
    callback delete-session(string);
    callback toggle-mark-session(string);
    callback handle-session-dialog(string, string);
    callback switch-session(string, string);
    callback switch-session-shortcut-inst(string);
    callback copy-session-chats(string);
    callback save-session-chats(string);
    callback remove-current-chats-last();

    callback show-session-archive-list(string);
    callback save-session-archive(string, string);
    callback delete-session-archive(string, string);
    callback delete-session-archives(string);
    callback show-session-archive(string, string);

    callback send-input-text(string);
    callback retry-send-input-text();
    callback delete-chat-item(string);
    callback toggle-mark-chat-item(string);
    callback stop-generate-text(string);
    callback code-text-items(string) -> [CodeTextItem];
    callback text-to-speech(string, string);
    callback clean-audio-cache();
    callback start-audio-record();
    callback stop-audio-record();
    callback play-audio-record();
    callback stop-audio-play();
    callback voice-to-text();

    callback show-message(string, string);
    callback copy-to-clipboard(string);
    callback handle-ok-cancel-dialog(string, string);

    callback setting-cancel();
    callback setting-ok(SettingDialogConfig);
}

