export struct ChatItem {
    utext: string,
    btext: string,
    etext: string,
}

export struct ChatSession {
    name: string,
    uuid: string,
}

export global Store  {
    in-out property<[ChatItem]> session-datas: [
        /* { utext: "Blue", btext: "user", etext:""}, */
        /* { uext: "Red",  btext: "bot", etext:""}, */
        /* { uext: "Green", btext: "user", etext:""}, */
        /* { uext: "Yellow", btext: "bot", etext:""}, */
    ];

    in-out property<string> chat-current-prompt: chat-prompts[0];
    in-out property<[string]> chat-prompts: [
        "Serve me as a chat bot.",
        "Serve me as a writing and programming assistant.",
    ];

    in-out property<[ChatSession]> chat-sessions: [ ];
    in-out property<string> input-text;
}

