import { Store } from "./store.slint";
import "./fonts/monospace.ttf";
import "./fonts/LXGWNeoXiHei.ttf";
import "./fonts/SourceHanSerifCN.ttf";

export global Theme  {
    out property<length> padding: 4px;
    out property<length> spacing: 4px;
    out property<length> left-panel-width: 350px;
    out property<length> header-height: 35px;
    out property<length> bottom-btn-height: header-height;
    out property<length> question-box-height: 100px;
    out property<length> border-radius: 4px;
    out property<length> scroll-width: 12px;
    out property<length> max-image-width: 300px;
    out property<color> dialog-background: lightgray.brighter(15%);

    in-out property<length> body-right-panel-width: 350px;

    in-out property<length> default-width: Store.setting-dialog-config.ui.win-width.to-float() * 1px;
    in-out property<length> default-height: Store.setting-dialog-config.ui.win-height.to-float() * 1px;
    in-out property<length> default-font-size: Store.setting-dialog-config.ui.font-size.to-float() * 1px;
    in-out property<length> enlarge-font-size: default-font-size + 1px;

    in-out property<string> default-font-family: Store.setting-dialog-config.ui.font-family;
    in-out property<string> code-font-family: "monospace";

    out property<length> icon-size: 24px;
    out property<length> default-label-width: 200px;
    out property<duration> default-animate-duration: 200ms;

    out property<color> brand-color: #409EFF;
    out property<color> success-color: #67C23A;
    out property<color> warning-color: #E6A23C;
    out property<color> danger-color: #F56C6C;
    out property<color> info-color: #909399;
    out property<color> mark-color: Theme.warning-color;
    out property<color> unmark-color: Colors.white;

    out property<color> hover-color: Colors.lightgray;
    out property<color> hover-color-dark: Colors.gray;
    out property<color> label-hover-color: Theme.light-fill-color.darker(10%);

    out property<color> primary-text-color: #303133;
    out property<color> regular-text-color: #606266;
    out property<color> secondary-text-color: #909399;
    out property<color> placeholder-text-color: #A8ABB2;
    out property<color> disabled-text-color: #C0C4CC;
    out property<color> darker-border-color: #CDD0D6;
    out property<color> dark-border-color: #D4D7DE;
    out property<color> base-border-color: #DCDFE6;
    out property<color> brand-border-color: #005FB8;
    out property<color> light-border-color: #E4E7ED;
    out property<color> lighter-border-color: #EBEEF5;
    out property<color> extra-light-border-color: #F2F6FC;

    out property<color> base-fill-color: #E5ECF1;
    out property<color> dark-fill-color: base-fill-color.darker(5%);
    out property<color> darker-fill-color: dark-fill-color.darker(5%);
    out property<color> light-fill-color: base-fill-color.brighter(5%);
    out property<color> lighter-fill-color: light-fill-color.brighter(5%);

    out property<color> extra-light-fill-color: #FAFCFF;
    out property<color> blank-fill-color: #FFFFFF;
    out property<color> basic-black-color: #000000;
    out property<color> basic-white-color: #FFFFFF;
    out property<color> page-background-color: #F2F3F5;
    out property<color> base-background-color: #FFFFFF;
    out property<color> overlay-background-color: #FFFFFF;

    public function toggle-archive-panel() {
        if (Theme.body-right-panel-width > 0) {
            Theme.body-right-panel-width = 0;
        } else {
            Theme.body-right-panel-width = 350px;
        }
    }

    public function toggle-sessions-panel() {
        if (Theme.left-panel-width > 0) {
            Theme.left-panel-width = 0;
        } else {
            Theme.left-panel-width = 350px;
        }
    }
}
