export global Theme  {
    out property<length> padding: 4px;
    out property<length> spacing: 4px;
    out property<length> left-panel-width: 400px;
    out property<length> bottom-panel-height: 200px ;
    out property<length> header-height: 40px ;
    in-out property<length> default-font-size: 18px;
    out property<length> default-width: 1500px;
    out property<length> default-height: 1000px;
    out property<length> border-radius: 8px;
}
