import { Store } from "./store.slint";

export global Theme  {
    out property<length> padding: 4px;
    out property<length> spacing: 4px;
    out property<length> left-panel-width: 400px;
    out property<length> bottom-panel-height: 150px;
    out property<length> question-box-height: bottom-panel-height;
    out property<length> header-height: 35px;
    out property<length> border-radius: 8px;
    out property<length> max-image-latex-width: 300px;
    out property<color> dialog-background: lightgray.brighter(15%);

    in-out property<length> bitem-left-padding: 100px;
    in-out property<length> uitem-right-padding: 300px;
    in-out property<length> body-right-panel-width: 350px;

    in-out property<length> default-width: Store.setting-dialog-config.ui.win-width.to-float() * 1px;
    in-out property<length> default-height: Store.setting-dialog-config.ui.win-height.to-float() * 1px;
    in-out property<length> default-font-size: Store.setting-dialog-config.ui.font-size.to-float() * 1px;

    out property<length> icon-size: 24px;

    out property<length> default-label-width: 100px;

    out property<color> brand-color: #409EFF;
    out property<color> success-color: #67C23A;
    out property<color> warning-color: #E6A23C;
    out property<color> danger-color: #F56C6C;
    out property<color> info-color: #909399;
    out property<color> mark-color: Colors.yellow;
    out property<color> unmark-color: Colors.white;

    out property<color> primary-text-color: #303133;
    out property<color> regular-text-color: #606266;
    out property<color> secondary-text-color: #909399;
    out property<color> placeholder-text-color: #A8ABB2;
    out property<color> disabled-text-color: #C0C4CC;
    out property<color> darker-border-color: #CDD0D6;
    out property<color> dark-border-color: #D4D7DE;
    out property<color> base-border-color: #DCDFE6;
    out property<color> light-border-color: #E4E7ED;
    out property<color> lighter-border-color: #EBEEF5;
    out property<color> extra-light-border-color: #F2F6FC;
    out property<color> darker-fill-color: #E6E8EB;
    out property<color> dark-fill-color: #EBEDF0;
    out property<color> base-fill-color: #F0F2F5;
    out property<color> light-fill-color: #F5F7FA;
    out property<color> lighter-fill-color: #FAFAFA;
    out property<color> extra-light-fill-color: #FAFCFF;
    out property<color> blank-fill-color: #FFFFFF;
    out property<color> basic-black-color: #000000;
    out property<color> basic-white-color: #FFFFFF;
    out property<color> page-background-color: #F2F3F5;
    out property<color> base-background-color: #FFFFFF;
    out property<color> overlay-background-color: #FFFFFF;

    public function toggle-archive-panel() {
        if (Theme.body-right-panel-width > 0) {
            Theme.body-right-panel-width = 0;
        } else {
            Theme.body-right-panel-width = 350px;
        }
    }

    public function resize-question-box(h: length) {
        if (Theme.bottom-panel-height >= h) {
            Theme.question-box-height = Theme.bottom-panel-height * 4;
        } else {
            Theme.question-box-height = Theme.bottom-panel-height;
        }
    }

}
