export struct Translation {
    new: string,
    save: string,
    edit: string,
    delete: string,

    send: string,
    stop: string,
    reset: string,
    clear: string,

    cancel: string,
    ok: string,

    setting: string,
    about: string,
    help: string,

    name: string,

    warning: string,
    delete-or-not: string,
    reset-or-not: string,

    record: string,
    recording: string,

    marked-success: string,
    unmarked-success: string,
    marked-failed: string,

    session-chat-copy-success: string,
    session-chat-enabled-auto-scroll-down: string,
    session-chat-disabled-auto-scroll-down: string,
    session-chat-stop: string,

    session-new-archive: string,
    archive-search-placeholder-text: string,

    setting-dialog-ui: string,
    setting-dialog-ui-font-size: string,
    setting-dialog-ui-win-WH: string,
    setting-dialog-ui-win-W: string,
    setting-dialog-ui-win-H: string,
    setting-dialog-ui-language: string,

    setting-dialog-chat: string,
    setting-dialog-chat-api-type: string,
    setting-dialog-chat-context-length: string,

    setting-dialog-audio: string,
    setting-dialog-audio-api-type: string,
    setting-dialog-audio-region: string,
    setting-dialog-audio-region-placeholder: string,
    setting-dialog-audio-cache-label: string,
    setting-dialog-audio-cache-clean-btn: string,
    setting-dialog-audio-input-devices-label: string,
    setting-dialog-audio-output-devices-label: string,
    setting-dialog-auto-to-text-enabled: string,
    setting-dialog-auto-to-text-disabled: string,
    setting-dialog-auto-play-record-enabled: string,
    setting-dialog-auto-play-record-disabled: string,
    setting-dialog-auto-speech-language-label: string,
    setting-dialog-audio-output-volume: string,

    setting-dialog-proxy: string,
    setting-dialog-proxy-openai-disabled: string,
    setting-dialog-proxy-openai-enabled: string,
    setting-dialog-proxy-azure-disabled: string,
    setting-dialog-proxy-azure-enabled: string,
    setting-dialog-proxy-type: string,
    setting-dialog-proxy-url: string,
    setting-dialog-proxy-url-placeholder: string,
    setting-dialog-proxy-port: string,
    setting-dialog-proxy-port-placeholder: string,

    session-default-name: string,

    session-new-dialog-title-new: string,
    session-new-dialog-title-edit: string,
    session-new-dialog-name: string,
    session-new-dialog-name-placeholder: string,
    session-new-dialog-api-model: string,
    session-new-dialog-shortcut-instruction: string,
    session-new-dialog-unused-history: string,
    session-new-dialog-used-history: string,
    session-new-dialog-system-prompt: string,
    session-new-dialog-preset-system-prompt-name: string,
    session-new-dialog-preset-system-prompt-chatbot-name: string,
    session-new-dialog-preset-system-prompt-chatbot: string,
}

export global Translator {
    in-out property<Translation> cn: {
        new: "新建",
        save: "保存",
        edit: "编辑",
        delete: "删除",

        send: "发送",
        stop: "停止",
        reset: "重置",
        clear: "清空",

        record: "录音",
        recording: "录音中",

        cancel: "取消",
        ok: "确定",

        setting: "设置",
        about: "关于",
        help: "帮助",

        name: "名称",

        warning: "警告",
        delete-or-not: "是否删除!",
        reset-or-not: "是否重置!",

        marked-success: "收藏成功!",
        unmarked-success: "取消收藏成功!",
        marked-failed: "收藏失败!",

        session-chat-copy-success: "复制会话成功!",
        session-chat-enabled-auto-scroll-down: "启用会话更新自动滚动!" ,
        session-chat-disabled-auto-scroll-down: "关闭会话更新自动滚动!",
        session-chat-stop: "正在停止会话...",

        session-new-archive: "新建归档",
        archive-search-placeholder-text: "输入关键词",

        setting-dialog-ui: "界面",
        setting-dialog-ui-font-size: "字体大小:",
        setting-dialog-ui-win-WH: "窗口大小:",
        setting-dialog-ui-win-W: "宽",
        setting-dialog-ui-win-H: "高",
        setting-dialog-ui-language: "选择语言:",

        setting-dialog-chat: "会话",
        setting-dialog-chat-api-type: "API类型:",
        setting-dialog-chat-context-length: "上下文长度:",

        setting-dialog-audio: "音频",
        setting-dialog-audio-api-type: "API类型:",
        setting-dialog-audio-region: "地区:",
        setting-dialog-audio-region-placeholder: "请输入服务所在地区",
        setting-dialog-audio-cache-label: "缓存占用:",
        setting-dialog-audio-cache-clean-btn: "清除缓存",
        setting-dialog-audio-input-devices-label: "输入设备:",
        setting-dialog-audio-output-devices-label: "输出设备:",
        setting-dialog-auto-to-text-enabled: "已启用录音自动转文字",
        setting-dialog-auto-to-text-disabled: "未启用录音自动转文字",
        setting-dialog-auto-play-record-enabled: "已启用自动播放录音",
        setting-dialog-auto-play-record-disabled: "未启用自动播放录音",
        setting-dialog-auto-speech-language-label: "录音语言:",
        setting-dialog-audio-output-volume: "播放音量:",

        setting-dialog-proxy: "代理",
        setting-dialog-proxy-openai-disabled: "OpenAI未启用代理",
        setting-dialog-proxy-openai-enabled: "OpenAI已启用代理",
        setting-dialog-proxy-azure-disabled: "Azure未启用代理",
        setting-dialog-proxy-azure-enabled: "Azure已启用代理",
        setting-dialog-proxy-type: "代理类型:",
        setting-dialog-proxy-url-placeholder: "请输入URL/IP:",
        setting-dialog-proxy-port: "端口:",
        setting-dialog-proxy-port-placeholder: "请输入端口",

        session-default-name: "默认会话",

        session-new-dialog-title-new: "新建会话",
        session-new-dialog-title-edit: "编辑会话",
        session-new-dialog-name: "名      称:",
        session-new-dialog-name-placeholder: "请输入会话名称",
        session-new-dialog-api-model: "API 模式:",
        session-new-dialog-shortcut-instruction: "快捷指令:",
        session-new-dialog-unused-history: "未启用历史会话模式",
        session-new-dialog-used-history: "已启用历史会话模式",
        session-new-dialog-system-prompt: "系统提示:",
        session-new-dialog-preset-system-prompt-name: "选择预定义提示",
        session-new-dialog-preset-system-prompt-chatbot-name: "通用聊天机器人",
    session-new-dialog-preset-system-prompt-chatbot: "你是一个通用聊天机器人。",
    };

    in-out property<Translation> en: {
        new: "New",
        save: "Save",
        edit: "Edit",
        delete: "Delete",

        send: "Send",
        stop: "Stop",
        reset: "Reset",
        clear: "Clear",

        record: "Record",
        recording: "Recording",

        cancel: "Cencel",
        ok: "Comfire",

        setting: "Setting",
        about:   "About   ",
        help:    "Help     ",

        name: "Name",

        warning: "Warning",
        delete-or-not: "Are You Sure to Delete!",
        reset-or-not: "Reset or not!",

        marked-success: "Marked Success!",
        unmarked-success: "Unmarked Success!",
        marked-failed: "Marked Failed!",

        session-chat-copy-success: "Copy Session Chat Success!",
        session-chat-enabled-auto-scroll-down: "Enabled Chats auto scroll to bottom when updating!" ,
        session-chat-disabled-auto-scroll-down: "Disabled Chats auto scroll to bottom when undating!",
        session-chat-stop: "Stop Chatting...",

        session-new-archive: "New Archive",
        archive-search-placeholder-text: "Input Keywrods",

        setting-dialog-ui: "UI",
        setting-dialog-ui-font-size: "Font Size:",
        setting-dialog-ui-win-WH: "Window Size:",
        setting-dialog-ui-win-W: "Width",
        setting-dialog-ui-win-H: "Height",
        setting-dialog-ui-language: "Language:",

        setting-dialog-chat: "Chat",
        setting-dialog-chat-api-type: "API Type:",
        setting-dialog-chat-context-length: "Context Length:",

        setting-dialog-audio: "Audio",
        setting-dialog-audio-api-type: "API Type:",
        setting-dialog-audio-region: "Region:",
        setting-dialog-audio-region-placeholder: "Please Input Service Region",
        setting-dialog-audio-cache-label: "Cache Used:",
        setting-dialog-audio-cache-clean-btn: "Clean Cache",
        setting-dialog-audio-input-devices-label: "Input Devices:",
        setting-dialog-audio-output-devices-label: "Output Devices:",
        setting-dialog-auto-to-text-enabled: "Auto Voice2Text Enabled",
        setting-dialog-auto-to-text-disabled: "Auto Voice2Text Disabled",
        setting-dialog-auto-play-record-enabled: "Auto Record Play Enabled",
        setting-dialog-auto-play-record-disabled: "Auto Record Play Disabled",
        setting-dialog-auto-speech-language-label: "Record Lang:",
        setting-dialog-audio-output-volume: "Play Volume:",

        setting-dialog-proxy: "Proxy",
        setting-dialog-proxy-openai-disabled: "Disabled OpenAI Proxy",
        setting-dialog-proxy-openai-enabled: "Enabled OpenAI Proxy",
        setting-dialog-proxy-azure-disabled: "Disabled Azure Proxy",
        setting-dialog-proxy-azure-enabled: "Enabled Azure Proxy",
        setting-dialog-proxy-type: "Type:",
        setting-dialog-proxy-url-placeholder: "URL/IP",
        setting-dialog-proxy-port: "Port:",
        setting-dialog-proxy-port-placeholder: "Port",

        session-default-name: "Default Session",

        session-new-dialog-title-new: "New Session",
        session-new-dialog-title-edit: "Edit Session",
        session-new-dialog-name: "Name:",
        session-new-dialog-name-placeholder: "Please Input Session Name",
        session-new-dialog-api-model: "API Model:",
        session-new-dialog-shortcut-instruction: "Shortcut Inst:",
        session-new-dialog-unused-history: "Disabled Hisotry Model",
        session-new-dialog-used-history: "Enabled History Model",
        session-new-dialog-system-prompt: "System Prompt:",

        session-new-dialog-preset-system-prompt-name: "Select Preset Prompt",
        session-new-dialog-preset-system-prompt-chatbot-name: "Service me as a chatbot.",
        session-new-dialog-preset-system-prompt-chatbot: "You are chatbot. Service me as best as you can.",
    };
}
