import { Theme } from "./theme.slint";

export global Util {
    public pure function text-color(type: string) -> color {
       if (type == "success") {
           return Theme.success-color;
       } else if (type == "warning") {
           return Theme.warning-color;
       } else if (type == "danger") {
            return Theme.danger-color;
       } else {
            return Theme.info-color;
       }
    }

    public pure function icon-color(type: string) -> image {
       if (type == "success") {
           return @image-url("./images/success.svg");
       } else if (type == "warning") {
           return @image-url("./images/warning.svg");
       } else if (type == "danger") {
           return @image-url("./images/danger.svg");
       } else {
           return @image-url("./images/info.svg");
       }
    }
}
