import { Theme } from "../theme.slint";
import { Header } from "./header.slint";
import { Body } from "./body/panel.slint";
import { Footer } from "./footer.slint";
import { ArchivePanel } from "./archive/panel.slint";

export component RPanel inherits VerticalLayout {
    spacing: Theme.spacing;
    in-out property question <=> footer.question;

    public function scroll-to-top() {
        body.scroll-to-top();
    }

    public function scroll-to-bottom() {
        body.scroll-to-bottom();
    }

    public function force-question-input-focus() {
        footer.force-focus();
    }

    HorizontalLayout {
        body := Body {}
        archPanel := ArchivePanel {}
    }

    footer := Footer {}
}

