import { Theme } from "../theme.slint";
import { Header } from "./header.slint";
import { Body } from "./body/panel.slint";
import { Footer } from "./footer.slint";
import { ArchivePanel } from "./archive/panel.slint";

export component RPanel inherits VerticalLayout {
    spacing: Theme.spacing;
    in-out property question <=> footer.question;
    in-out property chats-viewport-y <=> body.viewport-y;

    callback show-archive-panel();

    public function scroll-to-top() {
        body.scroll-to-top();
    }

    public function scroll-to-bottom() {
        body.scroll-to-bottom();
    }

    public function is-chats-on-bottom() -> bool {
        return body.is-chats-on-bottom();
    }

    public function force-question-input-focus() {
        footer.force-focus();
    }

    Rectangle {
        HorizontalLayout {
            Rectangle {
                body := Body {}
            }

            Rectangle {
                width: Theme.body-right-panel-width;
                archPanel := ArchivePanel {}
            }
        }
    }

    footer := Footer {
        scroll-to-top => {
            root.scroll-to-top()
        }

        scroll-to-bottom => {
            root.scroll-to-bottom()
        }

        show-archive-panel => {
            root.show-archive-panel();
        }
    }
}

