import { CDialog } from "../base/cdialog.slint";
import { Theme } from "../theme.slint";
import { Store } from "../store.slint";

export component HelpDialog inherits CDialog {
    visible: Store.help-dialog.show;

    title: Store.translator.help;
    title-bg: Theme.brand-color;
    width: 650px;
    height: 400px;

    rect := Rectangle {
        background: Theme.dialog-background;
        HorizontalLayout {
            padding: Theme.padding;
            Text {
                text: Store.help-dialog.text;
                wrap: word-wrap;
            }
        }
    }

    ok-clicked => {
        Store.help-dialog.show = false;
    }

    cancel-clicked => {
        Store.help-dialog.show = false;
    }
}
