import { CDialog } from "../base/cdialog.slint";
import { Theme } from "../theme.slint";
import { Store } from "../store.slint";

export component HelpDialog inherits CDialog {
    visible: Store.help-dialog.show;

    title: "帮助";
    title-bg: Theme.brand-color;
    width: 600px;
    height: 400px;

    rect := Rectangle {
        background: Theme.dialog-background;
        Text {
            wrap: word-wrap;
        }
    }

    ok-clicked => {
        Store.help-dialog.show = false;
    }

    cancel-clicked => {
        Store.help-dialog.show = false;
    }
}
