import { CDialog } from "../base/cdialog.slint";
import { Theme } from "../theme.slint";
import { Store } from "../store.slint";

export component IconDialog inherits CDialog {
    visible: Store.icon-dialog-setting.is-show;
    title: Store.translator.icon-dialog-title;
    title-bg: Theme.brand-color;
    width: (icon-size + icon-spacing) * column-count - icon-spacing + Theme.padding * 2;

    property<length> icon-size: 100px;
    property<length> icon-spacing: Theme.spacing;
    property<int> column-count: 6;

    callback select-index(int);

    flick := Flickable {
        height: 400px;
        viewport-height: (icon-size + icon-spacing) * Math.ceil(Store.icon-dialog-setting.icons.length / column-count) - icon-spacing + Theme.padding * 2;

        vbox := VerticalLayout {
            padding: Theme.padding;

            Rectangle {
                for icon[index] in Store.icon-dialog-setting.icons : Rectangle {
                    x: (icon-size + icon-spacing) * Math.mod(index, column-count);
                    y: (icon-size + icon-spacing) * Math.floor(index / column-count);
                    width: icon-size;
                    height: icon-size;
                    border-radius: Theme.border-radius;
                    background: touch.has-hover ? Theme.hover-color : Colors.transparent;

                    VerticalLayout {
                        alignment: center;
                        HorizontalLayout {
                            alignment: center;
                            Image {
                                width: icon-size * 0.5;
                                height: self.width;
                                colorize: Theme.regular-text-color;
                                source: icon;
                            }
                        }

                        HorizontalLayout {
                            alignment: center;
                            Text {
                                text: index + 1;
                                font-size: Theme.default-font-size;
                                color: Theme.regular-text-color;
                            }
                        }
                    }

                    touch := TouchArea {
                        clicked => {
                            root.select-index(index);
                            Store.icon-dialog-setting.is-show = false;
                        }
                    }
                }
            }
        }
    }

    cancel-clicked => {
        Store.icon-dialog-setting.is-show = false;
    }

    ok-clicked => {
        Store.icon-dialog-setting.is-show = false;
    }
}
