import { ComboBox } from "std-widgets.slint";
import { Theme } from "../../../theme.slint";
import { Store } from "../../../store.slint";
import { Azure } from "./azure.slint";
import { InputDevices } from "./input-devices.slint";
import { OutputDevices } from "./output-devices.slint";
import { Cache } from "./cache.slint";
import { Btn } from "../../../base/btn.slint";
import { Logic } from "../../../logic.slint";

export component Audio inherits Rectangle {
    width: 100%;
    height: 100%;

    property<length> label-width: Theme.default-label-width * 1.5;

    in-out property current-api-type-index <=> type-combox.current-index;

    in-out property azure-api-key <=> azure.api-key;
    in-out property azure-region <=> azure.region;

    in-out property current-input-device <=> input-devices.current-device;
    in-out property current-output-device <=> output-devices.current-device;
    in-out property is-auto-v2t <=> input-devices.is-auto-v2t;
    in-out property speech-language <=> input-devices.language;

    VerticalLayout {
        width: 100%;
        spacing: Theme.spacing * 3;

        HorizontalLayout {
            type-txt := Text {
                width: root.label-width;
                text: Store.translator.setting-dialog-audio-api-type;
            }

            type-combox := ComboBox {
                height: type-txt.preferred-height;
                model: Store.setting-dialog-config.audio.model;
                current-value: self.model[0];
                current-index: 0;
            }
        }

        VerticalLayout {
            vertical-stretch: 0;
            spacing: Theme.spacing;
            azure := Azure {
                visible: current-api-type-index == 0;
            }

            output-devices := OutputDevices {}
            input-devices := InputDevices {}

            Cache {}
        }

    }
}
