import { ComboBox } from "std-widgets.slint";
import { Theme } from "../../../theme.slint";
import { Store } from "../../../store.slint";
import { Azure } from "./azure.slint";
import { InputDevices } from "./input-devices.slint";
import { OutputDevices } from "./output-devices.slint";
import { Btn } from "../../../base/btn.slint";
import { Logic } from "../../../logic.slint";
import { Label } from "../../../base/label.slint";

export component Audio inherits Rectangle {
    width: 100%;
    height: 100%;

    property<length> label-width: Theme.default-label-width;

    in-out property current-api-type-index <=> type-combox.current-index;

    in-out property azure-api-key <=> azure.api-key;
    in-out property azure-region <=> azure.region;

    in-out property current-input-device <=> input-devices.current-device;
    in-out property current-output-device <=> output-devices.current-device;
    in-out property is-auto-v2t <=> input-devices.is-auto-v2t;
    in-out property is-auto-play-record <=> input-devices.is-auto-play-record;
    in-out property speech-language <=> input-devices.language;
    in-out property output-volume <=> output-devices.current-volume;

    VerticalLayout {
        spacing: Theme.spacing * 4;
        alignment: start;

        HorizontalLayout {
            type-txt := Label {
                width: root.label-width;
                text: Store.translator.setting-dialog-audio-api-type;
            }

            type-combox := ComboBox {
                model: Store.setting-dialog-config.audio.model;
                current-value: self.model[0];
                current-index: 0;
            }
        }

        azure := Azure {
            visible: current-api-type-index == 0;
        }

        output-devices := OutputDevices {}
        input-devices := InputDevices {}

        Btn {
            bg-color: Theme.danger-color;
            border-radius: Theme.border-radius;
            text: Store.translator.setting-dialog-audio-cache-clean-btn+ "("+ Store.cache.audio + ")";
            icon: @image-url("../../../images/warning.svg");
            clicked => {
                Logic.clean-audio-cache();
            }
        }

    }
}
