import { LineEdit } from "std-widgets.slint";
import { Theme } from "../../../theme.slint";
import { Store } from "../../../store.slint";
import { Label } from "../../../base/label.slint";

export component Azure inherits Rectangle {
    property<length> label-width: Theme.default-label-width;

    in-out property api-key <=> api-lineedit.text;
    in-out property region <=> region-lineedit.text;

    VerticalLayout {
        spacing: Theme.spacing * 4;
        alignment: start;

        HorizontalLayout {
            region-txt := Label {
                width: label-width;
                text: Store.translator.setting-dialog-audio-region;
            }

            region-lineedit := LineEdit {
                placeholder-text: Store.translator.setting-dialog-audio-region-placeholder;
            }
        }

        HorizontalLayout {
            api-txt := Label {
                width: label-width;
                text: "API Key:";
            }

            api-lineedit := LineEdit {
                placeholder-text: "API Key";
            }
        }

    }
}
