import { Theme } from "../../../theme.slint";
import { Store } from "../../../store.slint";
import { Btn } from "../../../base/btn.slint";
import { Logic } from "../../../logic.slint";

export component Cache inherits Rectangle {
    property<length> label-width: Theme.default-label-width * 1.5;

    width: 100%;

    HorizontalLayout {
        padding-top: Theme.padding * 4;
        VerticalLayout {
            alignment: center;
            width: 50%;
            HorizontalLayout {
                alignment: start;
                spacing: Theme.spacing;

                cache-label-txt := Text {
                    width: root.label-width;
                    text: Store.translator.setting-dialog-audio-cache-label;
                }

                VerticalLayout {
                    alignment: center;
                    cache-txt := Text {
                        text: Store.cache.audio;
                    }
                }
            }
        }

        HorizontalLayout {
            Btn {
                bg-color: Theme.danger-color;
                border-radius: Theme.border-radius;
                text: Store.translator.setting-dialog-audio-cache-clean-btn;
                icon: @image-url("../../../images/warning.svg");
                clicked => {
                    Logic.clean-audio-cache();
                }
            }
        }
    }
}
