import { ComboBox, CheckBox, Slider } from "std-widgets.slint";
import { Theme } from "../../../theme.slint";
import { Store } from "../../../store.slint";
import { Btn } from "../../../base/btn.slint";
import { Logic } from "../../../logic.slint";
import { Util } from "../../../util.slint";
import { Label } from "../../../base/label.slint";

export component OutputDevices inherits Rectangle {
    property<length> label-width: Theme.default-label-width;

    in-out property current-device <=> devices-combox.current-value;
    in-out property current-volume <=> volume-slider.value;

    VerticalLayout {
        spacing: Theme.spacing * 4;
        alignment: start;

        HorizontalLayout {
            HorizontalLayout {
                label-txt := Label {
                    width: root.label-width;
                    text: Store.translator.setting-dialog-audio-output-devices-label;
                }

                devices-combox := ComboBox {
                    height: label-txt.preferred-height;
                    model: Store.output-audio-devices;
                    current-value: Store.setting-dialog-config.audio.current-output-device;
                }
            }
        }

        HorizontalLayout {
            Label {
                width: label-width;
                text: Store.translator.setting-dialog-audio-output-volume;
            }

            volume-slider := Slider {
                minimum: 0;
                maximum: 200;
            }

            VerticalLayout {
                alignment: center;
                padding-left: Theme.padding * 4;
                width: Theme.default-font-size * 4;

                Label {
                    text: Math.round(volume-slider.value) / 100;
                }
            }
        }
    }
}
