import { Theme } from "../theme.slint";
import { Store } from "../store.slint";
import { Logic } from "../logic.slint";
import { IconBtn } from "../base/icon-btn.slint";

export component Body inherits Rectangle {
    private property<length> item-height: 45px;

    Flickable {
        viewport-height: Store.chat-sessions.length * root.item-height;

        for data[index] in Store.chat-sessions : VerticalLayout {
            y: index * item-height;
            height: root.item-height;

            Rectangle {
                background: data.uuid == Store.current-session-uuid ? Theme.base-background-color : (touch.has-hover ? Theme.light-fill-color.darker(10%) : Colors.transparent);

                touch := TouchArea {
                    clicked => {
                        Logic.switch-session(Store.current-session-uuid, data.uuid);
                    }
                }

                HorizontalLayout {
                    padding-left: Theme.padding * 2;
                    padding-right: Theme.padding * 2;

                    VerticalLayout {
                        alignment: center;
                        Text {
                            color: data.uuid == Store.current-session-uuid ? Theme.brand-color : Theme.basic-black-color;
                            text: data.name;
                            font-size: Theme.enlarge-font-size;
                        }
                    }

                    HorizontalLayout {
                        alignment: end;

                        VerticalLayout {
                            alignment: center;
                            IconBtn {
                                icon: @image-url("../images/star.svg");
                                colorize: data.is-mark ? Theme.mark-color : Theme.unmark-color;
                                clicked => {
                                    Logic.toggle-mark-session(data.uuid);
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
