import { Button, ListView,  TextEdit } from "std-widgets.slint";
import { Theme } from "../theme.slint";
import { Store } from "../store.slint";
import { TabBtn } from "../base/tab-btn.slint";

export component Bottom inherits HorizontalLayout {
    height: Theme.bottom-btn-height;

    TabBtn {
        height: root.height;
        icon: @image-url("../images/setting-fill.svg");
        clicked => {
            Store.setting-dialog-config.show = true;
        }
    }

    TabBtn {
        height: root.height;
        icon: @image-url("../images/about.svg");
        clicked => {
            Store.about-dialog.show = true;
        }
    }

    TabBtn {
        height: root.height;
        icon: @image-url("../images/help.svg");
        clicked => {
            Store.help-dialog.show = true;
        }
    }
}
