import { Button, ListView,  TextEdit } from "std-widgets.slint";
import { Theme } from "../theme.slint";
import { Store } from "../store.slint";
import { TabBtn } from "../base/tab-btn.slint";

export component Bottom inherits HorizontalLayout {
    alignment: space-around;
    TabBtn {
        height: Theme.bottom-btn-height;
        icon: @image-url("../images/setting-fill.svg");
        // text: Store.translator.setting-btn;
        clicked => {
            Store.setting-dialog-config.show = true;
        }
    }

    TabBtn {
        height: Theme.bottom-btn-height;
        icon: @image-url("../images/about.svg");
        // text: Store.translator.about-btn;
        clicked => {
            Store.about-dialog.show = true;
        }
    }

    TabBtn {
        height: Theme.bottom-btn-height;
        icon: @image-url("../images/help.svg");
        // text: Store.translator.help-btn;
        clicked => {
            Store.help-dialog.show = true;
        }
    }
}
