import { Theme } from "../theme.slint";
import { Store } from "../store.slint";
import { Logic } from "../logic.slint";
import { TabBtn } from "../base/tab-btn.slint";

export component Header inherits HorizontalLayout {
    TabBtn {
        height: Theme.header-height;
        text-color: Theme.regular-text-color;
        icon: @image-url("../images/addition.svg");
        clicked => {
            Logic.reset-edit-session();
            Store.session-dialog-setting.handle-type = "session-add";
            Store.session-dialog-setting.is-show = true;
        }
    }
    TabBtn {
        height: Theme.header-height;
        text-color: Theme.regular-text-color;
        icon: @image-url("../images/edit.svg");
        clicked => {
            Logic.set-edit-session(Store.current-session-uuid);
            Store.session-dialog-setting.handle-type = "session-edit";
            Store.session-dialog-setting.is-show = true;
        }
    }
    TabBtn {
        height: Theme.header-height;
        text-color: Theme.regular-text-color;
        icon: @image-url("../images/delete.svg");
        clicked => {
            Store.ok-cancel-dialog-setting.title-type = "warning";
            Store.ok-cancel-dialog-setting.title-text = Store.translator.warning;
            Store.ok-cancel-dialog-setting.body-text = Store.translator.delete-or-not;
            Store.ok-cancel-dialog-setting.handle-type = "session-item";
            Store.ok-cancel-dialog-setting.handle-uuid = Store.current-session-uuid;

        }
    }
}
