import { ListView } from "std-widgets.slint";
import { Theme } from "../theme.slint";
import { Store } from "../store.slint";
import { Logic } from "../logic.slint";
import { Btn } from "../base/btn.slint";
import { IconBtn } from "../base/icon-btn.slint";
import { Divider } from "../base/divider.slint";
import { Header } from "./header.slint";
import { Body } from "./body.slint";
import { Bottom } from "./bottom.slint";

import { StandardButton, Button } from "std-widgets.slint";

export component LPanel inherits Rectangle {
    width: Theme.left-panel-width;
    background: Theme.dark-fill-color;

    VerticalLayout {
        Header {}
        Divider {
            x: Theme.padding;
            height: 1px;
            width: root.width - Theme.padding * 2;
            background: Theme.regular-text-color;
        }

        Body {}
        Divider {
            x: Theme.padding;
            width: root.width - Theme.padding * 2;
        }
        Bottom { }
    }

}

