import { Theme } from "../../theme.slint";
import { Store } from "../../store.slint";
import { IconBtn } from "../../base/icon-btn.slint";
import { Logic } from "../../logic.slint";
import { CodeText } from "./code-text.slint";

export component BItem inherits VerticalLayout{
    in-out property text <=> txt.org-text;
    in-out property items <=> txt.items;
    in-out property<string> uuid;

    padding-left: self.width * Theme.bitem-left-padding;
    padding-right: Theme.padding * 2;
    spacing: Theme.spacing;

    HorizontalLayout {
        padding-bottom: Theme.padding;
        alignment: space-between;

        HorizontalLayout {
            alignment: end;
            padding-left: Theme.padding;
            spacing: Theme.spacing * 2;

            VerticalLayout {
                alignment: end;
                IconBtn {
                    icon: @image-url("../../images/copy.svg");
                    clicked => {
                        Logic.copy-to-clipboard(root.text);
                    }
                }
            }

            VerticalLayout {
                alignment: end;
                copy-icon := IconBtn {
                    icon: @image-url("../../images/speaker.svg");
                    clicked => {
                        Logic.text-to-speech(root.uuid, root.text);
                    }
                }
            }
        }

        Rectangle {
            height: img.width + 10px;
            width: img.width + 10px;
            border-radius: self.height / 2;
            background: Theme.basic-black-color;
            img := Image {
                width: Theme.icon-size;
                height: Theme.icon-size;
                image-fit: ImageFit.contain;
                source: @image-url("../../images/bot.svg");
                colorize: Colors.steelblue;
            }
        }
    }

    HorizontalLayout {
        Rectangle {
            background: Theme.dark-fill-color;
            border-radius: Theme.border-radius;

            TouchArea {
                clicked => {
                    Logic.copy-to-clipboard(root.text);
                }
            }

            VerticalLayout{
                padding: Theme.padding * 2;
                txt := CodeText { }
            }

        }
    }
}

