import { ListView } from "std-widgets.slint";
import { Theme } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { UItem } from "./uitem.slint";
import { BItem } from "./bitem.slint";

export component Body inherits ListView {
    function new-chat-text(utext: string, btext: string) -> string {
        return utext + "\n\n" + btext;
    }

    for data in Store.session-datas : VerticalLayout {
        padding-bottom: Theme.padding * 3;
        UItem {
            text: data.utext;
            uuid: data.uuid;
            is-mark: data.is-mark;

            copy-clicked => {
                Logic.copy_to_clipboard(root.new-chat-text(data.utext, data.btext));
            }
        }
        BItem { text: data.btext; }
    }
}

