import { Theme } from "../../theme.slint";
import { Store } from "../../store.slint";
import { IconBtn } from "../../base/icon-btn.slint";
import { Logic } from "../../logic.slint";

export component UItem inherits VerticalLayout{
    in-out property text <=> txt.text;

    padding-top: Theme.padding;
    padding-left: Theme.padding * 2;
    padding-right: self.width * 30%;
    spacing: Theme.spacing;

    HorizontalLayout {
        padding-bottom: Theme.padding;
        alignment: space-between;
        Rectangle {
            height: img.width + 10px;
            width: img.width + 10px;
            border-radius: self.height / 2;
            background: Theme.basic-black-color;
            img := Image {
                width: Theme.icon-size;
                height: Theme.icon-size;
                image-fit: ImageFit.contain;
                source: @image-url("../../images/user.svg");
                colorize: Colors.steelblue;
            }
        }

        HorizontalLayout {
            alignment: end;
            padding-right: Theme.padding;
            spacing: Theme.spacing * 2;

            VerticalLayout {
                alignment: end;
                IconBtn {
                    icon: @image-url("../../images/star.svg");
                    colorize: yellow;
                    clicked => {
                        Logic.show-message("success", "收藏成功！");
                    }
                }
            }

            VerticalLayout {
                alignment: end;
                IconBtn {
                    icon: @image-url("../../images/send.svg");
                }
            }

            VerticalLayout {
                alignment: end;
                IconBtn {
                    icon: @image-url("../../images/delete.svg");
                }
            }
        }
    }

    HorizontalLayout {
        Rectangle {
            background: Theme.light-fill-color;
            border-radius: Theme.border-radius;
            VerticalLayout{
                padding: Theme.padding * 2;
                txt := Text {
                    color: Theme.primary-text-color;
                    font-size: Theme.default-font-size + 2px;
                    wrap: word-wrap;
                }
            }
        }
    }
}

