import { LineEdit, Slider } from "std-widgets.slint";
import { Theme } from "../../../theme.slint";
import { Store } from "../../../store.slint";

export component Azure inherits Rectangle {
    width: 100%;
    height: 100%;
    property<length> label-width: Theme.default-label-width * 2;

    in-out property api-key <=> api-lineedit.text;
    in-out property url <=> url-lineedit.text;
    in-out property max-tokens <=> tokens-slider.value;
    in-out property temperature <=> temp-slider.value;
    in-out property frequency-penalty <=> frequency-slider.value;
    in-out property presence-penalty <=> presence-slider.value;

    VerticalLayout {
        width: 100%;
        spacing: Theme.spacing * 3;

        HorizontalLayout {
            api-txt := Text {
                width: label-width;
                text: "API Key:";
            }

            api-lineedit := LineEdit {
                height: api-txt.preferred-height + Theme.padding;
                placeholder-text: "API Key";
            }
        }

        HorizontalLayout {
            url-txt := Text {
                width: label-width;
                text: "API URL:";
            }

            url-lineedit := LineEdit {
                height: url-txt.preferred-height + Theme.padding;
                placeholder-text: "API URL";
            }
        }

        HorizontalLayout {
            Text {
                width: label-width;
                text: "Max Tokens:";
            }

            tokens-slider := Slider {
                minimum: 128;
                maximum: 3968;
            }

            VerticalLayout {
                alignment: center;
                padding-left: Theme.padding * 4;
                width: Theme.default-font-size * 4;

                Text {
                    text: Math.floor(tokens-slider.value);
                }
            }
        }

        HorizontalLayout {
            Text {
                width: label-width;
                text: "Temperature:";
            }

            temp-slider := Slider {
                minimum: 0;
                maximum: 200;
            }

            VerticalLayout {
                alignment: center;
                padding-left: Theme.padding * 4;
                width: Theme.default-font-size * 4;

                Text {
                    text: Math.round(temp-slider.value) / 100;
                }
            }
        }

        HorizontalLayout {
            Text {
                width: label-width;
                text: "Frequency:";
            }

            frequency-slider := Slider {
                minimum: -200;
                maximum: 200;
            }

            VerticalLayout {
                alignment: center;
                padding-left: Theme.padding * 4;
                width: Theme.default-font-size * 4;

                Text {
                    text: Math.round(frequency-slider.value) / 100;
                }
            }
        }

        HorizontalLayout {
            Text {
                width: label-width;
                text: "Presence:";
            }

            presence-slider := Slider {
                minimum: -200;
                maximum: 200;
            }

            VerticalLayout {
                alignment: center;
                padding-left: Theme.padding * 4;
                width: Theme.default-font-size * 4;

                Text {
                    text: Math.round(presence-slider.value) / 100;
                }
            }
        }
    }
}
