import { ComboBox } from "std-widgets.slint";
import { Theme } from "../../../theme.slint";
import { Store } from "../../../store.slint";
import { OpenAI } from "./openai.slint";

export component Chat inherits Rectangle {
    width: 100%;
    height: 100%;

    in-out property current-api-type-index <=> type-combox.current-index;
    in-out property openai-api-key <=> openai.api-key;
    in-out property openai-url <=> openai.url;
    in-out property openai-max-tokens <=> openai.max-tokens;
    in-out property openai-temperature <=> openai.temperature;
    in-out property openai-frequency-penalty <=> openai.frequency-penalty;
    in-out property openai-presence-penalty <=> openai.presence-penalty;

    VerticalLayout {
        width: 100%;
        spacing: Theme.spacing * 3;

        HorizontalLayout {
            type-txt := Text {
                width: Theme.default-label-width * 2;
                text: Store.translator.setting-dialog-chat-api-type;
            }

            type-combox := ComboBox {
                height: type-txt.preferred-height;
                model: Store.session-dialog-setting.api-model;
                current-value: self.model[0];
                current-index: 0;
            }
        }

        Rectangle {
            openai := OpenAI {
                visible: current-api-type-index == 0;
            }
        }
    }
}
