import { Theme } from "../theme.slint";

export component Btn inherits Rectangle {
    in-out property<string> text <=> txt.text;
    in-out property icon <=> img.source;
    in-out property font-size <=> txt.font-size;

    in-out property<color> bg-color: Theme.brand-color;
    in-out property<color> bg-hover-color: bg-color.darker(30%);
    in-out property<color> bg-pressed-color: bg-color.darker(50%);
    in-out property<color> text-color: Colors.white;

    callback clicked <=> touch.clicked;

    background: touch.pressed ? bg-pressed-color : touch.has-hover ? bg-hover-color : bg-color;
    height: txt.preferred-height * 1.33;

    animate background {
        duration: Theme.default-animate-duration;
        easing: ease-in-out;
    }

    Rectangle {
        img := Image {
            width: root.icon.width > 0 ? txt.height - Theme.padding : 0;
            x: txt.x - Theme.icon-size - Theme.spacing * 2;
            colorize: root.text-color;
        }

        txt := Text {
            x: (parent.width - self.width) / 2 + img.width / 2 + (root.icon.width > 0 ? Theme.spacing * 2 : 0);
            color: root.text-color;
            font-size: Theme.enlarge-font-size;
        }
    }
    touch := TouchArea { }
}
