import { Theme } from "../theme.slint";
import { Store } from "../store.slint";
import { Btn } from "./btn.slint";

export component CDialog inherits Rectangle {
    in-out property title <=> txt.text;
    in-out property<color> title-bg: Theme.brand-color;
    in-out property<bool> is-hide-btns: false;

    callback cancel-clicked();
    callback ok-clicked();

    visible: false;
    width: 450px;
    height: 300px;
    background: Theme.base-background;

    VerticalLayout {
        Rectangle {
            height: txt.preferred-height * 1.33;
            background: root.title-bg;
            txt := Text {
                color: Colors.white;
                font-size: Theme.default-font-size + 1px;
            }
        }

        VerticalLayout {
            @children
        }

        if (!is-hide-btns) : Rectangle {
            background: root.background;
            HorizontalLayout {
                cancel-btn := Btn {
                    text: Store.translator.cancel;
                    bg-color: Theme.danger-color;
                    border-width: 0;
                    icon: @image-url("../images/cancel.svg");
                    clicked => { root.cancel-clicked(); }
                }

                Btn {
                    text: Store.translator.ok;
                    border-width: 0;
                    icon: @image-url("../images/success.svg");
                    clicked => { root.ok-clicked(); }
                }
            }
        }
    }
}
