import { Theme } from "../theme.slint";
import { Store } from "../store.slint";
import { Btn } from "./btn.slint";

export component CDialog inherits Rectangle {
    in-out property<length> body-width: 450px;
    in-out property<length> body-height: 300px;
    in-out property title <=> txt.text;
    in-out property<color> title-bg: Theme.brand-color;

    callback cancel-clicked();
    callback ok-clicked();

    visible: false;
    width: self.visible ? root.body-width : 0;
    height: self.visible ? root.body-height : 0;
    background: Theme.base-background-color;

    VerticalLayout {
        Rectangle {
            height: txt.preferred-height * 1.33;
            background: root.title-bg;
            txt := Text {
                color: Colors.white;
                font-size: Theme.default-font-size + 1px;
            }
        }

        VerticalLayout {
            @children
        }

        HorizontalLayout {
            spacing: Theme.spacing;
            Btn {
                text: Store.translator.cancel;
                bg-color: Theme.danger-color;
                border-width: 0;
                icon: @image-url("../images/cancel.svg");
                clicked => { root.cancel-clicked(); }
            }

            Btn {
                text: Store.translator.ok;
                border-width: 0;
                icon: @image-url("../images/success.svg");
                clicked => { root.ok-clicked(); }
            }
        }
    }
}
