import { Theme } from "../theme.slint";
import { Tip } from "./tip.slint";

export component IconBtn inherits Rectangle {
    in-out property icon <=> img.source;
    in-out property colorize <=> img.colorize;
    in-out property icon-width <=> img.width;
    in-out property icon-rotation-angle <=> img.rotation-angle;
    in-out property mouse-cursor <=> touch.mouse-cursor;
    out property has-hover <=> touch.has-hover;

    in-out property tip-pos <=> tip.pos;
    in-out property tip-text <=> tip.text;
    in-out property tip-is-show <=> tip.is-show;

    callback clicked <=> touch.clicked;

    in-out property<bool> checked: false;
    in-out property<color> bg-color: transparent;
    in-out property<color> hover-color: Theme.hover-color;
    in-out property<color> bg-pressed-color: hover-color.darker(50%);

    width: Theme.icon-size;
    height: self.width;
    border-radius: self.width / 3;
    background: touch.pressed || root.checked ? bg-pressed-color : touch.has-hover ? hover-color : bg-color;

    animate background {
        duration: Theme.default-animate-duration;
        easing: ease-in-out;
    }

    tip := Tip {
        pwidth: root.width;
        pheight: root.height;
        is-show: touch.has-hover;
    }

    img := Image {
        width: root.width * 0.8;
        colorize: Theme.basic-black-color;
    }

    touch := TouchArea {
        mouse-cursor: self.has-hover ? pointer : default;
    }
}
