import { Theme } from "../theme.slint";

// Warning: animation will cause high used cpu rate
export component LivingCircle inherits Rectangle {
    in-out property<length> size: 16px;
    in-out property<duration> duration: 500ms;
    in-out property<color> bgcolor: Theme.danger-color;

    property<bool> is-start: false;
    property<int> iter-count: 0;

    public function start() {
        root.visible = true;
        root.iter-count = -1;

        if (root.is-start) { return; }

        root.is-start = true;
        root.width = root.size;
        root.height = root.size;
    }

    public function stop() {
        root.iter-count = 0;
        root.visible = false;
    }

    width:  root.size * 0.8;
    height: root.size * 0.8;
    border-radius: self.size / 2;
    background: is-start ? root.bgcolor : Colors.transparent;

    animate width, height {
        duration: root.duration;
        iteration-count: root.iter-count;
    }
}

