export global BaseLogic {
    pure callback line-count(string) -> int;
    line-count => {
        return 0;
    }

    pure callback code-line-text(string) -> string;
    code-line-text => {
        return "";
    }

    pure callback list_item_trim(string) -> string;
    list_item_trim(text) => {
        return text;
    }

    pure callback leading-spaces(string) -> string;
    leading-spaces => {
        return "";
    }
}

