import { Theme } from "../theme.slint";

export component TabBtn inherits Rectangle {
    in-out property<string> text <=> txt.text;
    in-out property icon <=> img.source;

    in-out property<bool> checked: false;
    in-out property<color> text-color: Theme.brand-color;
    in-out property<color> text-hover-color: text-color.darker(30%);
    in-out property<color> text-checked-color: text-color.darker(100%);

    callback clicked <=> touch.clicked;

    HorizontalLayout {
        spacing: Theme.spacing;

        VerticalLayout {
            alignment: center;
            img := Image {
                height: Theme.enlarge-font-size;
                width: self.height;
                colorize: root.checked ? text-checked-color : touch.has-hover ? text-hover-color : text-color;

                animate colorize {
                    duration: Theme.default-animate-duration;
                    easing: ease-in-out;
                }
            }
        }

        VerticalLayout {
            alignment: center;
            txt := Text {
                color: root.checked ? text-checked-color : touch.has-hover ? text-hover-color : text-color;
                font-size: Theme.default-font-size;

                animate color {
                    duration: Theme.default-animate-duration;
                    easing: ease-in-out;
                }
            }
        }
    }

    touch := TouchArea {
        mouse-cursor: self.has-hover ? pointer : default;
    }
}
