import { SpinBox, LineEdit, CheckBox, ComboBox } from "std-widgets.slint";
import { Theme } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Label } from "../../base/label.slint";

export component UI inherits Rectangle {
    in-out property font-size <=> font-size-spin-box.value;
    in-out property font-family <=> fonts-combox.current-value;
    in-out property win-width <=> win-width-lineedit.text;
    in-out property win-height <=> win-height-lineedit.text;
    in-out property<string> language: Store.setting-dialog-config.ui.language;

    public function set-language(lang :string) {
        if (lang == "en") {
            cn-checkbox.checked = false;
            en-checkbox.checked = true;
        } else {
            cn-checkbox.checked = true;
            en-checkbox.checked = false;
        }
    }

    VerticalLayout {
        spacing: Theme.spacing * 4;
        alignment: start;

        HorizontalLayout {
            window-size-txt := Label {
                width: Theme.default-label-width;
                text: Store.translator.setting-dialog-ui-win-WH;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;
                win-width-lineedit := LineEdit {
                    placeholder-text: Store.translator.setting-dialog-ui-win-W;
                }

                Label {
                    text: "x";
                }

                win-height-lineedit := LineEdit {
                    placeholder-text: Store.translator.setting-dialog-ui-win-H;
                }
            }
        }

        HorizontalLayout {
            font-size-txt := Label {
                width: Theme.default-label-width;
                text: Store.translator.setting-dialog-ui-font-size;
            }

            font-size-spin-box := SpinBox {
                minimum: 10;
                maximum: 50;
            }
        }

        HorizontalLayout {
            Label {
                width: Theme.default-label-width;
                text: Store.translator.setting-dialog-ui-font-family;
            }

            fonts-combox := ComboBox {
                model: ["SystemDefault", "SourceHanSerifCN"];
                current-value: self.model[0];
                current-index: 0;
            }
        }

        HorizontalLayout {
            Label {
                width: Theme.default-label-width;
                text: Store.translator.setting-dialog-ui-language;
            }

            cn-checkbox := CheckBox {
                text: "中文";
                checked: root.language != "en";
                toggled => {
                    if (!self.checked) {
                        self.checked = true;
                        return;
                    }

                    en-checkbox.checked = !self.checked;
                    root.language = "cn";
                }
            }

            en-checkbox := CheckBox {
                text: "English";
                checked: root.language == "en";
                toggled => {
                    if (!self.checked) {
                        self.checked = true;
                        return;
                    }

                    cn-checkbox.checked = !self.checked;
                    root.language = "en";
                }
            }
        }
    }
}
