import { SpinBox, LineEdit, CheckBox } from "std-widgets.slint";
import { Theme } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Label } from "../../base/label.slint";

export component UI inherits Rectangle {
    in-out property font-size <=> font-size-spin-box.value;
    in-out property win-width <=> win-width-lineedit.text;
    in-out property win-height <=> win-height-lineedit.text;
    in-out property<string> language: Store.setting-dialog-config.ui.language;

    public function set-language(lang :string) {
        if (lang == "en") {
            cn-checkbox.checked = false;
            en-checkbox.checked = true;
        } else {
            cn-checkbox.checked = true;
            en-checkbox.checked = false;
        }
    }

    VerticalLayout {
        spacing: Theme.spacing * 4;
        alignment: start;

        HorizontalLayout {
            height: Store.setting-dialog-config.ui.language == "cn" ? window-size-txt.preferred-height : window-size-txt.preferred-height * 1.33;
            VerticalLayout {
                alignment: center;
                window-size-txt := Label {
                    width: Theme.default-label-width;
                    text: Store.translator.setting-dialog-ui-win-WH;
                }
            }

            HorizontalLayout {
                width: 30%;
                spacing: Theme.spacing * 2;
                win-width-lineedit := LineEdit {
                    placeholder-text: Store.translator.setting-dialog-ui-win-W;
                }

                VerticalLayout {
                    alignment: center;
                    Label {
                        text: "x";
                    }
                }
                win-height-lineedit := LineEdit {
                    placeholder-text: Store.translator.setting-dialog-ui-win-H;
                }
            }
        }

        HorizontalLayout {
            height: Store.setting-dialog-config.ui.language == "cn" ? font-size-txt.preferred-height : font-size-txt.preferred-height * 1.33;
            VerticalLayout {
                alignment: center;
                font-size-txt := Label {
                    width: Theme.default-label-width;
                    text: Store.translator.setting-dialog-ui-font-size;
                }
            }

            font-size-spin-box := SpinBox {
                width: 15%;
                minimum: 15;
                maximum: 50;
            }
        }

        HorizontalLayout {
            VerticalLayout {
                alignment: center;
                Label {
                    width: Theme.default-label-width;
                    text: Store.translator.setting-dialog-ui-language;
                }
            }

            cn-checkbox := CheckBox {
                text: "中文";
                checked: root.language != "en";
                toggled => {
                    en-checkbox.checked = !self.checked;
                    if (self.checked) {
                        root.language = "cn";
                    }
                }
            }

            en-checkbox := CheckBox {
                text: "English";
                checked: root.language == "en";
                toggled => {
                    cn-checkbox.checked = !self.checked;
                    if (self.checked) {
                        root.language = "en";
                    }
                }
            }

        }

    }
}
